server:
  port: 8050

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: demo
          uri: https://gitee.com
          predicates:
            - Path=/test

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
