server:
  port: 8050

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=2
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: GET, POST
        - id: sudoku-service
          uri: lb://sudoku-service
          predicates:
            - Path=/api/sudoku/**
          filters:
            - StripPrefix=2
            - name: Retry
              args:
                retries: 3
                status: BAD_GATEWAY
                methods: GET, POST



#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8000/eureka/
