server:
  port: 8002
spring:
  application:
    name: user-service
    # 数据源
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stms
    hikari:
      maximum-pool-size: 10

# Eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/