server:
  port: 8003

spring:
  application:
    name: sudoku-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # 数据源
  datasource:
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stms
    hikari:
      maximum-pool-size: 10

# Eureka
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8000/eureka/

mybatis-plus:
  type-enums-package: com.carlosli.sudoker.sudoku.constant